framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: false

    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    php_errors:
        log: true
    assets:
        version: '%env(ASSET_VERSION)%'
