vich_uploader:
    db_driver: orm

    mappings:
        partner_image:
            uri_prefix: /uploads/partner
            upload_destination: '%kernel.project_dir%/public/uploads/partner'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        mention_image:
            uri_prefix: /uploads/mention
            upload_destination: '%kernel.project_dir%/public/uploads/mention'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true