web_controllers:
    resource: ../../src/Controller/Web/
    type: annotation
    name_prefix: web_

admin_controllers:
    resource: ../../src/Controller/Admin/
    type: annotation
    name_prefix: admin_
    prefix: /admin

kernel:
    resource: ../../src/Kernel.php
    type: annotation
