web_redirect_index:
    path: /
    controller: App\Controller\Web\LocaleRedirectController
    defaults:
        route: 'web_index'

web_redirect_presse:
    path: /presse
    controller: App\Controller\Web\LocaleRedirectController
    defaults:
        route: 'web_press'