web_imprint:
    path:
        en: /imprint
        de: /impressum
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: web/static/imprint.html.twig
    methods: GET

web_privacy:
    path:
        en: /privacy
        de: /datenschutz
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: web/static/privacy.html.twig
    methods: GET
