web_imprint:
    path: /impressum
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: index/impressum.html.twig
    methods: GET

web_privacy:
    path: /datenschutz
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: index/datenschutz.html.twig
    methods: GET

web_account_confirm:
    path: /account-bestaetigen
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: emails/account-confirm.html.twig
    methods: GET

